version: '3.8'

services:

  front:
    build: ./front
    ports:
      - "4200:4200"

  db:
    container_name: db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: unifor
      POSTGRES_USER: root
      POSTGRES_PASSWORD: senha
    networks:
      - rede

  back:
    build:
      context: ./back
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/unifor
    depends_on:
      - db
    networks:
      - rede

networks:
  rede:
    driver: bridge